### ISSUE TITLE
Does not work with adb sideload

### ISSUE THREAD

**Issue by hacker1024** [Zackptg5/Disable_FEC_DmVerity#11]
`adb sideload` renames the sideloaded zip to `package.zip`. As the script depends on the zip filename to enable/disable things, it does nothing.

**Comment by Zackptg5** [comment]
True. When would you need to sideload it though versus normal twrp flash? I only support twrp for this zip, I'm not able to test any others

**Comment by hacker1024** [comment]
On a few devices that I've used, TWRP does not mount /sdcard properly after formatting /data, until Android has booted once. If you copy any files to /sdcard beforehand, they end up in /data/media/ instead of /data/media/0/ after Android boots - so it's easy to forget about them, and they take up space.

Because of this, I usually try not to copy anything to /sdcard after formatting /data before booting Android - hence why I sideloaded.

**Comment by hacker1024** [comment]
> I only support twrp for this zip, I'm not able to test any others

I'm using TWRP's sideload option.

**Comment by Zackptg5** [comment]
I'll add a volume key selection for sideload installs and post a test build here when ready

**Comment by Zackptg5** [comment]
[Disable_Dm-Verity_ForceEncrypt_12.23.2019-test.zip](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3996789/Disable_Dm-Verity_ForceEncrypt_12.23.2019-test.zip)

Can you try this build? I'm unable to test it myself currently but it should trigger volkey selection if the zip is named "package.zip"

**Comment by hacker1024** [comment]
It didn't work, just defaulted to removing force encrypt and keeping everything else

**Comment by Zackptg5** [comment]
Got the chance to test it out myself and found the problems (there were 2 oversights :/ )

This one should do the trick

[Disable_Dm-Verity_ForceEncrypt_12.23.2019-test.zip](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3997108/Disable_Dm-Verity_ForceEncrypt_12.23.2019-test.zip)

**Comment by hacker1024** [comment]
That one works perfectly, thanks.

**Comment by Zackptg5** [comment]
Great, I'll add this into the next version :)
