### ISSUE TITLE
disable forceencrypt breaks encryption

### ISSUE THREAD

**Issue by aIecxs** [Zackptg5/Disable_FEC_DmVerity#12]
undo 5a07e10 [related](https://github.com/topjohnwu/Magisk/issues/2394)

**Comment by aIecxs** [comment]
according to [fs_mgr_fstab.cpp](https://android.googlesource.com/platform/system/core/+/master/fs_mgr/fs_mgr_fstab.cpp) flags are defined as

    { "encryptable=",       MF_CRYPT },
    { "forceencrypt=",      MF_FORCECRYPT },
    { "forcefdeorfbe=",     MF_FORCEFDEORFBE },
    { "fileencryption=",    MF_FILEENCRYPTION },

it seems that `encryptable=` `forceencrypt=` and `forcefdeorfbe=` are always pointing to crypto footer,
while `fileencryption=` is always passing encryption mode. i came to the conclusion that `forcefdeorfbe=` is (always?) handled as FDE, but in case it is converted into FBE as a consequence the fstab must changed to `fileencryption=` afterwards (or crypto footer is simply ignored then?)

the MF_FORCEFDEORFBE is (besides the force of FDE) afaik only used for converting into FBE. if we replace it we won't break FDE, only losing the availbility to convert (someone needs to test or digging more into sources).

it is most likely safe to replace `forceencrypt=` and `forcefdeorfbe=` with `encryptable=` please reverse this change.

regarding `fileencryption=` to me it looks (because of the naming of flags) is not forcing encryption.
i think it is safe to say that this flag must not be replaced with encryptable, furthermore i believe it must not replaced at all. 

    fs_mgr_is_encryptable()
    encryptable=    // The encryptable flag is followed by an = and the  location of the keys
                    // returns fs_mgr_flags.crypt, MF_CRYPT

    fs_mgr_is_encryptable()
    forceencrypt=   // The forceencrypt flag is followed by an = and the location of the keys
                    // returns fs_mgr_flags.force_crypt, MF_FORCECRYPT

    fs_mgr_is_encryptable()
    fs_mgr_is_convertible_to_fbe()
    forcefdeorfbe=  // The forcefdeorfbe flag is followed by an = and the location of the keys
                    // returns fs_mgr_flags.force_fde_or_fbe, MF_FORCEFDEORFBE,
                    // encryption_options = (aes default)

    fs_mgr_is_file_encrypted()
    fileencryption= // The fileencryption flag is followed by an = and the encryption_options
                    // returns fs_mgr_flags.file_encryption, MF_FILEENCRYPTION,
                    // encryption_options = (see below)

    keydirectory=   // The metadata flag is followed by an = and the directory for the keys
                    // returns metadata_key_dir = (arg)
    
if you know that `fileencryption=` forces encryption (has someone ever tested?) i recommend to delete the whole strings either than just deleting the flag name. furthermore for FBE+metadata encryption the `keydirectory=` string should be deleted too. in any case i won't see this as a fix because it removes the availbility of optional encryption completely instead of just disabling the forcing (it just makes more sence than the current `sed -i s/fileencryption=/=/g`).

the following arguments can be passed (iterate bottom up when deleting)

    encryption_options:

    fileencryption= // (not specified, is using aes default)

    fileencryption=ice
    fileencryption=ice,keydirectory=/metadata/vold/metadata_encryption

    fileencryption=aes-256-xts             // (not specified, is using aes default)
    fileencryption=aes-256-xts:aes-256-cts // (aes default)
    fileencryption=aes-256-xts:aes-256-heh
    fileencryption=aes-256-xts:adiantum

    fileencryption=adiantum                // (not specified, is using adiantum default)
    fileencryption=adiantum:adiantum       // (adiantum default)
    fileencryption=adiantum:aes-256-cts
    fileencryption=adiantum:aes-256-heh

@osm0sis i like your testing against FDE or FBE but it does only reflect the current state userdata partition. consider testing against

    getprop ro.crypto.type = block
    getprop ro.crypto.type = file

(and if really needed)

    getprop ro.crypto.state = encrypted
    getprop ro.crypto.state = unencrypted

regarding dm-verity please note the current sed will break `verifyatboot` and `avb_keys=` flags. the following flags exist

    verifyatboot
    verify
    avb_keys=
    avb
    fsverity

furthermore i recommend to change fstab line-by-line, only lines starting with / and only lines matching fstabv2 (and maybe fstabv1) layout should processed, this way it will preserve comments

**Comment by osm0sis** [comment]
Why you @'ing me? This ain't my baby. 🙂

**Comment by aIecxs** [comment]
Oops! I Did It Again...
b-cuz u touchd util_functions recently and maybe @topjohnwu cares more about new design these days? or maybe the coding style looks like yours? anyway we need ur insights... my device is 32-bit nougat and don't have that much experience

**Comment by osm0sis** [comment]
This is @Zackptg5's project and his area he's looked into, so I'm sure he can handle it.

**Comment by aIecxs** [comment]
@Zackptg5 of course you are addressed in the 1st place, thats's why i place this here instead of magisk

**Comment by aIecxs** [comment]
i have also seen combinations
[twrp.fstab](https://github.com/TeamWin/android_device_motorola_ocean/blob/android-9.0/recovery/root/etc/twrp.fstab) fileencryption=ice:aes-256-cts
[twrp.fstab](https://github.com/TeamWin/android_device_asus_I01WD/blob/lineage-16.0/recovery/root/etc/twrp.fstab) fileencryption=ice:aes-256-cts;keydirectory=/metadata/vold/metadata_encryption
[recovery.fstab](https://github.com/TeamWin/android_device_asus_I01WD/blob/lineage-16.0/recovery.fstab) fileencryption=ice,wrappedkey,keydirectory=/metadata/vold/metadata_encryption

**Comment by Zackptg5** [comment]
This is for @topjohnwu to look at. Good stuff, well made issue (they're becoming more uncommon haha) :)
This is stuff in magiskboot which is why I'm saying it's a topjohnwu thing. My mod uses that and then performs the same patches on vendor fstabs

**Comment by Zackptg5** [comment]
@aIecxs 
fileencryption flag does force encryption - I've been able to test this one myself on my oneplus 5t and no 7 pro.
Originally the flags were all replaced with encryptable but that caused weird glitches in some roms and so it was just removed but having the whole string removed seems like a good idea

**Comment by aIecxs** [comment]
Thx for testing, sadly that means we are left with no option to preserve encryption while disabling (FBE) force encryption :(

except you tell me FBE encryption is working without `fileencryption=`

it seems that invalid flags are ignored, so instead of trying to replace the whole string we could just replace with any keyword, this would give the availbility to restore encryption on need. or at least, replace the leftover `=` with `#` or something. for example `magiskfixnofbe=` or `fbedisableflag=` it's same length for hexpatching ;)

(accidentially closed this issue i should really stop typing while driving)

meanwhile figured out that `ro.crypto.state` was used in the initial release [f7b4935](https://github.com/topjohnwu/Magisk/commit/f7b4935) so `ro.crypto.type` probably won't work too, forget this part

**Comment by Zackptg5** [comment]
I'll take a look into this when I get the chance this week or next :)

**Comment by Zackptg5** [comment]
@aIecxs So I'm looking into this but the one thing I don't get is:
Why disable forced encryption if you're planning on encrypting later?

**Comment by aIecxs** [comment]
basically every second rooting tutorial in the www is based on patching boot with Magisk Manager, which currently ends up in boot loop and data loss. as before v7.3.5 this wasn't the case

you might have noticed the increasing noobs requests on android enthusiasts and xda, i bet a lot of these problems are related to this. advanced users blame noobs for not following tut's

probably it affects magisk too. i wonder how this bug could survive for so long.

however the current workaround is simple: keep force encryption

at a minimum requirement i would expect the "keep force encryption" checkbox as default, or a proper announcement that the usage of Magisk Manager has changed.

_i tried older versions of Magisk Manager but they are unusable because they forces you to update latest release (at least on the stable channel)_
meanwhile figured out. install [v7.3.4](https://github.com/topjohnwu/Magisk/releases/download/manager-v7.3.4/MagiskManager-v7.3.4.apk) goto Settings - update channel - custom - paste this url
https://raw.githubusercontent.com/topjohnwu/magisk_files/2df48954f8098a52304d0e60de3f0c16bcc3ef69/stable.json

luckily other disablers like multidisabler, no-verity-opt-encrypt, dm-verity-disabler-treble still can successful disable forceencrypt without breaking encryption

to answer the question, there is not really a need to keep encryption with force encryption disabled, it's more about the usage problem.

there are rare cases where it is required, the most common i know is changing the FDE default_password:

1. format data
2. disable force encryption
3. set a screen lock
4. encrypt device

after this TWRP is asking for lock screen credentials and is no more longer able to decrypt with _default_password_. there might be other methods for this but this is the only noob-friendly method i know

**Comment by Zackptg5** [comment]
Had the chance to look more into it. I could replace the removals with 'encryptable' for forceencrypt and forcefdeorfbe in the vendor fstab patching (magiskboot's a different story - I don't much cpp). Fileencryption is a different beast altogether. Just removing the flag turns it into an invalid flag which is silently ignore - which is sort of what we want - ignores encryption. I'll look into a better alternative though

**Comment by aIecxs** [comment]
that's the main problem - we don't know what's really patched in the end, it's always a guesswork which files need to restored. kind of uninstaller or backup would be a nice feature. or, as suggested, use dummy flag for easy undo

**Comment by Zackptg5** [comment]
So after doing some more research and consulting to some people more knowledgeable on it. Here's what will/can happen:
forceencrypt and forcefdeofbe will be change to encryptable
fileencryption will stay as is

The problem is that there's no way for fileencryption flag to be changed to something optional and still work the same. Either you have it, or you don't. This zip still has the name flags as always so you can just remove the 'ForceEncrypt' part from the zipname to keep encryption

**Comment by aIecxs** [comment]
what about broken `verifyatboot` and `avb_keys=`

**Comment by Zackptg5** [comment]
Whoops, forgot about those. I'll add those in. Only problem is that I don't know how to modify magisk boot for the encryptable flags so I'll likely not change any of that - users who flash this mod to remove encryption shouldn't encrypt

**Comment by Zackptg5** [comment]
@aIecxs I added the verity flags to this, can you verify that it works as intended (don't know why it wouldn't but just to be sure)
[Disable_Dm-Verity_ForceEncrypt_02.24.2020.zip](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/4246675/Disable_Dm-Verity_ForceEncrypt_02.24.2020.zip)

**Comment by aIecxs** [comment]
confirmed. however, you forgot the `encryptable=`

**Comment by Zackptg5** [comment]
I decided to not do that in order to keep the behavior consistent with magiskboot. If you want to encrypt, remove the 'ForceEncrypt' part from the zipname to keep encryption

**Comment by aIecxs** [comment]
that does not work it's destroying fstab anyway. the default setting is always false for formatted data and true for encrypted data

**Comment by aIecxs** [comment]
maybe you can answer Technical and Technerd360, my answer would be manually create folder `/data/unencrypted` before flashing this zip

https://forum.xda-developers.com/showthread.php?t=3817389&page=82

**Comment by DonHStanley0923** [comment]
What are y'all working on? Maybe I could help. Had something like this come about quite a few times throughout several different timespans here. I believe one involved a ship in the 1500s.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DonHStanley0923** [comment]
Crashed in on my GrandMa's farm... I think...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DonHStanley0923** [comment]
Bunch of highdollar royal blooded banned Huskies... Lol

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DonHStanley0923** [comment]
There's the great grandmother's, sister's that are older than them... They drank blood. They're half 👽 of darkness part 👼 and mostly do things by the book like their fathers' before them... Or maybe this is all too old for y'all...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aIecxs** [comment]
Please change your passwords and run your antivirus program!

**Comment by Zackptg5** [comment]
Reported and blocked, I'm leaving them up so github staff or whoever can see it

**Comment by Zackptg5** [comment]
@aIecxs Sorry for being slow to respond. I nuked my phone so it's getting RMAd currently :(
