### ISSUE TITLE
Redmi note 6 pro

### ISSUE THREAD

**Issue by sayaadali** [Zackptg5/Disable_FEC_DmVerity#2]
Please give support to redmi note 6 pro (tulip)

**Comment by Zackptg5** [comment]
What doesn't work? Since this mod uses magisk tools, compatibility is limited to devices compatible with magisk

**Comment by sayaadali** [comment]
Data encryption is not working and also can we get lazyflasher sir  when we install ROM we got recovery replacement

**Comment by Zackptg5** [comment]
Nope. lazyflasher can't do everything the zip does. I'm going to need logs (recovery log after flashing the zip). if your recovery is getting replaced, that's your rom doing it, not this zip. Delete system/bin/install-recovery.sh to prevent that
