### ISSUE TITLE
can not boot

### ISSUE THREAD

**Issue by qianjie1990** [Zackptg5/Disable_FEC_DmVerity#3]
use the newest package, magisk 18.0,xiaomi mix2s can not boot, only miloop

**Comment by Zackptg5** [comment]
Can you post the recovery log after flashing it? Is your device compatible with magisk?

**Comment by qianjie1990** [comment]
> Can you post the recovery log after flashing it? Is your device compatible with magisk?

Thank you very much for your efforts. 
my mix2s is flashed magisk 18.0, after this can not boot,recovery log is ok
now,xiaomi mix3 can flash magisk 17.1\17.3, but after flash this,it is  only show  MIX.

**Comment by Zackptg5** [comment]
I'm not entirely sure what you are trying to say.
This mod uses magisk 18 tools so if you're device does not work with magisk 18, then this mod may not work either.
Are you saying that magisk 18 does not work but 17 does for you device? If so, I can put together a build with magisk 17 tools for you to test

**Comment by qianjie1990** [comment]
> I'm not entirely sure what you are trying to say.
> This mod uses magisk 18 tools so if you're device does not work with magisk 18, then this mod may not work either.
> Are you saying that magisk 18 does not work but 17 does for you device? If so, I can put together a build with magisk 17 tools for you to test

sorry,my bad english. your latest code magisk18 does not work, 17 work for mix2s but not work for mix3. Did I make myself clear?

**Comment by Zackptg5** [comment]
Yup :) I'm not the developer of the magisk tools unfortunately so I can't help you there. 

If you need magisk 17 tools, you can just download the magisk 17 zip and replace the magiskboot and magiskinit binaries in the disable dmverity zip. It should work for you then (scripting is the same so the binaries would be all you need to change)

**Comment by qianjie1990** [comment]
> Yup :) I'm not the developer of the magisk tools unfortunately so I can't help you there.
> 
> If you need magisk 17 tools, you can just download the magisk 17 zip and replace the magiskboot and magiskinit binaries in the disable dmverity zip. It should work for you then (scripting is the same so the binaries would be all you need to change)

thanks a lot,i will try
