### ISSUE TITLE
Not working on pixel 3 with android 9.

### ISSUE THREAD

**Issue by giantpune** [Zackptg5/Disable_FEC_DmVerity#6]
This produces a zip file.  When I flash a pixel phone with factory images and then use twrp to flash this zip file, the device complains about data is corrupt and refuses to boot.  The zip works as expected on pixel 1 and pixel2, but on pixel 3, its not working.  FWIW, the magisk installer works fine on this phone, even back to version 17.3.

Am I missing a step?
```sh
$ git clone git@github.com:Zackptg5/Disable_Dm-Verity_ForceEncrypt.git fec
$ cd fec
$ zip -r ../disable_verity_fec.zip . -x *.git*
```

```sh
+ adb shell twrp install /tmp/disable_verity_fec.zip
Installing zip file '/tmp/disable_verity_fec.zip'
Checking for Digest file...
Skipping Digest check: no Digest file found
*************************************************
* DmVerity,ForceEncrypt, and DiscQuota Disabler *
*                 By: Zackptg5                  *
*         Heavily based on the work of:         *
*            TopJohnWu and Jcadduono            *
*************************************************
- Current boot slot: _a
- Mounting /system, /vendor
- Device is system-as-root
- Target image: /dev/block/sda11
- Creating/modifying .magisk and .supersu files...
- Unpacking boot image
- Disabling selections in vendor fstabs...
  Patching: /system/vendor/etc/fstab.persist
  Patching: /system/vendor/etc/fstab.sdm845
- Patching ramdisk
- Removing dm(avb)-verity in dtb
- Repacking boot image
- Flashing new boot image
- DTBO image: /dev/block/sde11
- Unmounting partitions
- Done
Done processing script file
```

**Comment by Zackptg5** [comment]
Looks fine to me. I recommend using the zips I already made though just to rule out compression issues : zackptg5.com/android.php#disverfe

**Comment by giantpune** [comment]
I tried again using your zip.  Flash factory images to the device, boot up latest twrp image, flash your zip, when I go to reboot the device, it throws an error and refuses to boot.  Even verified directly before installing the sha1sum of the file to make sure it was corrupt somehow in transfer.

```sh
$ adb shell sha1sum /tmp/disable_verity_fec.zip
98dc79656fc4d85824670485fb517e4fcd4fc912  /tmp/disable_verity_fec.zip
$ adb shell twrp install /tmp/disable_verity_fec.zip
Installing zip file '/tmp/disable_verity_fec.zip'
Checking for Digest file...
Skipping Digest check: no Digest file found
*************************************************
* DmVerity,ForceEncrypt, and DiscQuota Disabler *
*                 By: Zackptg5                  *
*         Heavily based on the work of:         *
*            TopJohnWu and Jcadduono            *
*************************************************
- Current boot slot: _a
- Mounting /system, /vendor
- Device is system-as-root
- Target image: /dev/block/sda11
- Creating/modifying .magisk and .supersu files...
- Unpacking boot image
- Disabling selections in vendor fstabs...
  Patching: /system/vendor/etc/fstab.persist
  Patching: /system/vendor/etc/fstab.sdm845
- Patching ramdisk
- Removing dm(avb)-verity in dtb
- Repacking boot image
- Flashing new boot image
- DTBO image: /dev/block/sde11
- Unmounting partitions
- Done
Done processing script file

```
![image](https://user-images.githubusercontent.com/543833/55419226-4a0bca80-5542-11e9-9690-a1d2f51e2a79.png)

**Comment by Zackptg5** [comment]
Log looks good. The device shouldn't even try to encrypt so there's the main problem. Did you format data first? (Different from wipe data).

Can you attach your boot img and fstabs? I won't be able to look at them till probably next week though cause my pc's in the shop

**Comment by giantpune** [comment]
The boot.img is the one thats installed when you flash the zip from google.
https://developers.google.com/android/images#blueline
https://dl.google.com/dl/android/aosp/blueline-pq2a.190305.002-factory-b8869812.zip

When I flash the images, I can boot directly into twrp and flash magisk no problem.  The device will work as expected.  But if I start over from the beginning and try to add your encryption disable, then thats when the device refuses to boot.

I'm not sure where to find the fstab for you.  Which file would that be inside?

This same sequence of actions is working fine on the pixel 1 and 2 still.  It seems like we're missing some bit to make it work on the pixel 3.

**Comment by Zackptg5** [comment]
Can you try today's version? Something changed in the busybox binary so grep logic wasn't detecting kernel fstabs
