### ISSUE TITLE
Modify the script to preserve selinux context

### ISSUE THREAD

**Issue by fawazahmed0** [Zackptg5/Disable_FEC_DmVerity#8]
Hi Zackptg5,
It was causing no network issue, as the selinux context in nvdata fstab was changed to u:object_r:unlabeled:s0 , I had to change it back to u:object_r:nvdata_file:s0 to make everything work.

By God's grace , I have little knowledge of linux, so I was able to figure it out, but other guys who had this device (realme 3) had to go to service center and they were told the phone has to be replaced (ofcourse for free as it's still under warranty)

**Comment by Zackptg5** [comment]
Hmm, context shouldn't have been changed but I'll look into it, thanks. Did you use stable or latest test build? https://forum.xda-developers.com/showpost.php?p=79919222&postcount=500

**Comment by fawazahmed0** [comment]
@Zackptg5 I have used this Disable_Dm-Verity_ForceEncrypt_05.21.2019.zip, I assume this is stable version

**Comment by fawazahmed0** [comment]
I see sed command is being used in the script to replace the strings,  I have tested in my linux vm, sed does not preserve selinux context

**Comment by fawazahmed0** [comment]
I would use something like this to fetch selinux of a file and store in some variable
somevar=ls -Z filename | awk '{print $1}'
Later after doing the sed editing, 
I will use something like this to set the selinux context back:
chcon $somevar filename

**Comment by fawazahmed0** [comment]
Test build https://forum.xda-developers.com/showpost.php?p=79919222&postcount=500  , does not work, it does not patch the fstab
[Disabledmveritytestbuild.log](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3427438/Disabledmveritytestbuild.log)

**Comment by Zackptg5** [comment]
That's a great idea! I'll use that for chcon of all of the fstabs
In your log, it looks like system didn't mount properly and that busted mounting of nvdata.

Can you try this test build? I don't expect the outcome to be any different but it should tell me what the actual error is with system mounting
[Disable_Dm-Verity_ForceEncrypt_07.24.2019.zip](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3427796/Disable_Dm-Verity_ForceEncrypt_07.24.2019.zip)

**Comment by fawazahmed0** [comment]
Here is the recovery log for stable build zip
[disableveritystablebuild.log](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3427807/disableveritystablebuild.log)

Everything works perfectly in this except the selinux context gets changed, anyways I can manually edit it from twrp adb shell.
Just one more thing, after flash your stable build, it shows these lines in twrp adb shell:
WARNING: linker: Warning: couldn't read "/system/etc/ld.config.txt" for "/sbin/t
oybox" (using default configuration instead): error reading file "/system/etc/ld
.config.txt": Too many symbolic links encountered

Any time I enter any command in twrp adb shell, I get these lines, I am not sure what these lines means. Anyways thanks for your script

**Comment by fawazahmed0** [comment]
> 
> 
> That's a great idea! I'll use that for chcon of all of the fstabs
> In your log, it looks like system didn't mount properly and that busted mounting of nvdata.
> 
> Can you try this test build? I don't expect the outcome to be any different but it should tell me what the actual error is with system mounting
> [Disable_Dm-Verity_ForceEncrypt_07.24.2019.zip](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3427796/Disable_Dm-Verity_ForceEncrypt_07.24.2019.zip)

Testing now,wait

**Comment by fawazahmed0** [comment]
@Zackptg5 
[07.24.2019testbuild.log](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3427843/07.24.2019testbuild.log)
Here is the log for 07.24.2019 test build

**Comment by Zackptg5** [comment]
Hmm okay. I think I see the problem so hopefully this'll fix it. Try this zip and send me the log too (it has your file context fix in it btw)
[Disable_Dm-Verity_ForceEncrypt_07.24.2019.zip](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3427890/Disable_Dm-Verity_ForceEncrypt_07.24.2019.zip)

**Comment by fawazahmed0** [comment]
> 
> 
> Hmm okay. I think I see the problem so hopefully this'll fix it. Try this zip and send me the log too (it has your file context fix in it btw)
> [Disable_Dm-Verity_ForceEncrypt_07.24.2019.zip](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3427890/Disable_Dm-Verity_ForceEncrypt_07.24.2019.zip)

[07.24.2019v2testbuild.log](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3427929/07.24.2019v2testbuild.log)
This one works like stable build now, but the selinux context of fstab still got changed to u:object_r:unlabeled:s0, so network was not working

**Comment by fawazahmed0** [comment]
ok I see the problem in your script 
it should be some thing like:
PERM="$(ls -Z $i | awk '{print $1}')"
and not
PERM="$(ls -z $i | awk '{print $1}')"

Z should be uppercase

wait I will test and see, if that works

**Comment by fawazahmed0** [comment]
ok, the problem is in busybox ls, which is stripped down version of ls,  it does not support -Z  (selinux) flag

**Comment by fawazahmed0** [comment]
@Zackptg5 This one works perfectly:
PERM="$(/sbin/ls -Z $i | awk '{print $1}')"

Kindly update the script :)

**Comment by fawazahmed0** [comment]
@Zackptg5 one more thing, awk '{print $1}' works only in my phone, other phones might have selinux context in other fields like awk '{print $3}' , you might have to use pattern matching or something else.
selinux context follows this pattern:  `:*:*:`

**Comment by Zackptg5** [comment]
Thanks for the tip, I have to be specific with it though because TWRP includes different binaries on different devices. It looks like toybox ls has it and is probably what you have in your TWRP. Lots of older ones have busybox instead so I'll need to include it in the zip then.
 What else would be outputted other than the security context and filename for toybox ls? It should be all that's outputted for toybox

**Comment by Zackptg5** [comment]
Okay, got toybox bundled in for it's ls applet so give this a try

[Disable_Dm-Verity_ForceEncrypt_07.24.2019.zip](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3428972/Disable_Dm-Verity_ForceEncrypt_07.24.2019.zip)

**Comment by fawazahmed0** [comment]
> 
> 
> Okay, got toybox bundled in for it's ls applet so give this a try
> 
> [Disable_Dm-Verity_ForceEncrypt_07.24.2019.zip](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3428972/Disable_Dm-Verity_ForceEncrypt_07.24.2019.zip)


@Zackptg5 
Great idea to use toybox, now ls output will be consistent across all the devices.
Coming to your new zip, log message showing many errors in it, I guess maybe just a syntax error in your script.It got stopped in middle with error 1
Also the selinux thing does not work in your new zip. selinux got changed to ? for fstab

[07-24-19v3.txt](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3431939/07-24-19v3.txt)

**Comment by fawazahmed0** [comment]
ok I have used your previous zip and added toybox in it and changed /sbin/ls to $bin/toybox ls, and everything works perfectly fine , i.e selinux context is preserved
[v2log.txt](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3432068/v2log.txt)
[Disable_Dm-Verity_ForceEncrypt_07.24.2019v2.zip](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3432070/Disable_Dm-Verity_ForceEncrypt_07.24.2019v2.zip)

**Comment by fawazahmed0** [comment]
ok, the problem is in your compiled toybox, it prints ?  instead of printing selinux context, don't know why that's happening, toybox in my twrp sbin print's selinux context properly

**Comment by Zackptg5** [comment]
Looks like syntax error and some more mounting problems :/
I grabbed those binaries from the official site too - I'll test them out more and figure something out

**Comment by fawazahmed0** [comment]
@Zackptg5 ok I have used your previous zip (as it gives no syntax error) and added twrp compiled toybox in the zip (copied from /sbin) and now everything works perfectly fine , i.e selinux context is preserved etc.

**Comment by Zackptg5** [comment]
Can you try this one (replace toybox with yours for now) and see if it all works as intended? Think I got the mounting stuff fixed here (and stupid syntax error)

[Disable_Dm-Verity_ForceEncrypt_07.25.2019.zip](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3432566/Disable_Dm-Verity_ForceEncrypt_07.25.2019.zip)

**Comment by fawazahmed0** [comment]
> 
> 
> Can you try this one (replace toybox with yours for now) and see if it all works as intended? Think I got the mounting stuff fixed here (and stupid syntax error)
> 
> [Disable_Dm-Verity_ForceEncrypt_07.25.2019.zip](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3432566/Disable_Dm-Verity_ForceEncrypt_07.25.2019.zip)

yeah works perfectly fine, provided I copy my twrp toybox in it, maybe it will be better to compile toybox from android source

**Comment by fawazahmed0** [comment]
ok, wait, I will get the toybox for you

**Comment by fawazahmed0** [comment]
I tried fetching the toybox from arm gsi, but it does not work, I guess it depends on dynamic libraries to work

**Comment by Zackptg5** [comment]
Guess that makes sense. I looked into a different avenue and restorecon may do what we want. Give this a go and see if it works - no toybox required
[Disable_Dm-Verity_ForceEncrypt_07.25.2019.zip](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3433121/Disable_Dm-Verity_ForceEncrypt_07.25.2019.zip)

**Comment by Zackptg5** [comment]
Scratch that last one, restorecon didn't work initially and I then found that it was a part of toybox.
Then had the 'duh' moment - toybox is in /system/bin on every marshmallow and newer rom so I can just use it so this one may finally fit the bill.
[Disable_Dm-Verity_ForceEncrypt_07.25.2019.zip](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3433666/Disable_Dm-Verity_ForceEncrypt_07.25.2019.zip)

**Comment by fawazahmed0** [comment]
> 
> 
> Scratch that last one, restorecon didn't work initially and I then found that it was a part of toybox.
> Then had the 'duh' moment - toybox is in /system/bin on every marshmallow and newer rom so I can just use it so this one may finally fit the bill.
> [Disable_Dm-Verity_ForceEncrypt_07.25.2019.zip](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3433666/Disable_Dm-Verity_ForceEncrypt_07.25.2019.zip)

@Zackptg5 I think that might not work, because binaries in /system/bin depends on dynamic libraries.
Before flashing the script, I tried mount the system and then tried executing '/system/bin/toybox ls -Z' using twrp adb shell and it didn't worked. Someone has to compile the toybox, I have complete Omni source at my vm, I would have done it, but I have many bad sectors in my harddisk, starting vm causes blue screen problem.

**Comment by fawazahmed0** [comment]
If I solve my blue screen problem, then I will compile the arm version

**Comment by Zackptg5** [comment]
It worked for me when I tested it, did you try it? Since system and vendor are mounted all of the dependencies should be there I would think.

I'd need arm and x86 builds if you're able to build

**Comment by fawazahmed0** [comment]
> 
> 
> It worked for me when I tested it, did you try it? Since system and vendor are mounted all of the dependencies should be there I would think.
> 
> I'd need arm and x86 builds if you're able to build

Sorry, I thought it will not work , so didn't test it, because restoring things back to stock is a pain in this device as the twrp restore doesn't work and I have to use fastboot to restore.

Yeah, I just tested it now, it works perfectly. Do you still need toybox builds? I will do that when the pc gets working again. please confirm

**Comment by Zackptg5** [comment]
Nope, no toybox needed. Toybox is included in all roms that it would be required in (oreo+) so we should be good to go. I'll drop the next test build on xda (same as the last one I posted here). Thanks a ton for all of the help and troubleshooting!

**Comment by chankruze** [comment]
Good discussion !

**Comment by Zackptg5** [comment]
@fawazahmed0 osm0sis (developer of ak3) reworked some of the system_root mounting stuff and wanted to know if it works now so could you test this out when you get the chance? Thanks
[Disable_Dm-Verity_ForceEncrypt_08.11.2019.zip](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3490113/Disable_Dm-Verity_ForceEncrypt_08.11.2019.zip)

**Comment by fawazahmed0** [comment]
@Zackptg5  You asked at the right time.
I flashed the zip, and It did not work. Here is log

[dmverity_08_11_2019.txt](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3490223/dmverity_08_11_2019.txt)

I tried dmvertiy_08.02.2019.zip yesterday and that one worked for me.

**Comment by fawazahmed0** [comment]
@Zackptg5 
It's trying to mount system from wrong location
It shouldn't be :
/dev/block/bootdevice/by-name/system

It should mount from: 
/dev/block/by-name/system
or
/dev/block/platform/bootdevice/by-name/system

**Comment by Zackptg5** [comment]
/dev/block/bootdevice should symlink to proper path. Can you post recovery log after flashing this so I could forward it to osm0sis? Thanks

**Comment by fawazahmed0** [comment]
> 
> 
> @Zackptg5 You asked at the right time.
> I flashed the zip, and It did not work. Here is log
> 
> [dmverity_08_11_2019.txt](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3490223/dmverity_08_11_2019.txt)
> 
> I tried dmvertiy_08.02.2019.zip yesterday and that one worked for me.

@Zackptg5 Here is the log

**Comment by Zackptg5** [comment]
Thanks, I'll forward it on to him

**Comment by Zackptg5** [comment]
@fawazahmed0 
Talked to osm0sis and I think he got a better solution worked out. How's this one work (log as before) 
[Disable_Dm-Verity_ForceEncrypt_08.11.2019.zip](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3490599/Disable_Dm-Verity_ForceEncrypt_08.11.2019.zip)
Thanks!

**Comment by fawazahmed0** [comment]
@Zackptg5 
This one worked, Here is the log:
[dm_verity_v2_08_11_2019.txt](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3490926/dm_verity_v2_08_11_2019.txt)

**Comment by fawazahmed0** [comment]
@Zackptg5 @osm0sis Today I flashed a new twrp build , with these new changes:
https://github.com/fawazahmed0/android_device_Realme3_RMX1821/commit/b4aceb09094663bf56e88d21be5d0e6052afd197

I then tried the dmverity.zip and it did not work, I guess the problem is in how the twrp mounts the partitions.

Previouly, my twrp mounted system partition at /system (wrong way to mount for system as root devices, but still many SAR devices uses this in their twrp fstab)
The zip works perfectly well in the above setup. Here is the log
[dmverity_08_11_19_v2_no_systemroot.txt](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3494089/dmverity_08_11_19_v2_no_systemroot.txt)

In my newly build twrp, the system partition is mounted at /system_root (right way to mount for SAR devices, I can now execute /system/bin binaries through twrp shell, as everything is mounted properly)
The zip didn't work in the above setup. Here is the log:
[dm_verity_08_11_19_v2_with_systemrootmount.txt](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3494103/dm_verity_08_11_19_v2_with_systemrootmount.txt)

**Comment by osm0sis** [comment]
Your device TWRP maintainer needs to fix it so you have the correct links in `/dev/block` for a SAR device. Yours has `/dev/block/platform/bootdevice` for some reason where the correct symlink is `/dev/block/bootdevice` and always has been.

Your ongoing issues boil down to "broken TWRP is broken" so that's where the burden of resolving them should go.

Edit: Also I think you need to revert the fstab change in the commit you linked.

**Comment by fawazahmed0** [comment]
@osm0sis Thanks for pointing that, I have solved the bootdevice mount thing for now:
https://github.com/fawazahmed0/android_device_Realme3_RMX1821/commit/1dd4bef3cef501b84c1c003663f46d2220985e44

Coming to fstab change, I guess that is the right way to mount in SAR devices, for example see here:
https://github.com/TeamWin/android_device_oppo_RMX1851/commit/0d20a8113a067f80b0894e12ebe83d8b3f8d354b

https://github.com/TeamWin/android_device_xiaomi_violet/commit/581fb3d598fbc477d84f6d5edebb8ad930aa716d

https://github.com/TeamWin/android_device_xiaomi_perseus/commit/8d2e63b919bb8fd3986bbd5cb7e085e12f76f6cc

I will ask about this in slack, let's see what they reply

**Comment by Zackptg5** [comment]
Looks like the path is figured out :)
This this will be next release if it works for you:
[Disable_Dm-Verity_ForceEncrypt_08.13.2019.zip](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3498194/Disable_Dm-Verity_ForceEncrypt_08.13.2019.zip)

**Comment by fawazahmed0** [comment]
@Zackptg5 Doesn't seem to work
Here is the log:
[dm_verity_08_13_2019.txt](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3498584/dm_verity_08_13_2019.txt)

**Comment by fawazahmed0** [comment]
@osm0sis @Zackptg5  I am not sure, how AK script works, but  I was trying to understand how opengapps works in /system and /system_root mount without throwing any error.
This is what I got:


if [ -n "$(cat /proc/cmdline | grep slot_suffix)" ];
then
  device_abpartition=true
  SYSTEM_MOUNT=/system
  SYSTEM=$SYSTEM_MOUNT/system
  VENDOR=/vendor/vendor
elif [ -n "$(cat /etc/fstab | grep /system_root)" ];
then
  device_abpartition=false
  SYSTEM_MOUNT=/system_root
  SYSTEM=$SYSTEM_MOUNT/system
  VENDOR=/vendor
else
  device_abpartition=false
  SYSTEM_MOUNT=/system
  SYSTEM=$SYSTEM_MOUNT
  VENDOR=/vendor
fi

**Comment by Zackptg5** [comment]
Log is saying that system wasn't found in the fstab. Can you try this one and post log? I added some debug lines to it
[Disable_Dm-Verity_ForceEncrypt_08.13.2019.zip](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3498632/Disable_Dm-Verity_ForceEncrypt_08.13.2019.zip)

**Comment by fawazahmed0** [comment]
@Zackptg5 Here is the log: [dmverity_08_13_19_v2.txt](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3498670/dmverity_08_13_19_v2.txt)

**Comment by Zackptg5** [comment]
Looks like it's an issue with your twrp. /system isn't present in the fstab so it isn't getting mounted. Magisk installer and other zips will likely fail too

**Comment by fawazahmed0** [comment]
@Zackptg5 nope, magisk is working, tested it today

**Comment by Zackptg5** [comment]
Hmm, it uses a similar method. Here's the error:
`/tmp/anykernel/tools/busybox mount -o rw -t auto /system
mount: can't find /system in /etc/fstab`

That command should work in twrp

**Comment by fawazahmed0** [comment]
Give me that magisk zip, with debugging enabled  , I will post the log here

**Comment by Zackptg5** [comment]
[Magisk-v19.3debugmount.zip](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3498715/Magisk-v19.3debugmount.zip)

**Comment by fawazahmed0** [comment]
[Magisklog.txt](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3498726/Magisklog.txt)

**Comment by Zackptg5** [comment]
Looks like magisk does it differently. I'm not exactly sure what normal twrp setup is but it looks like you did remove system from the fstab here: https://github.com/fawazahmed0/android_device_realme_spartan/commit/99b158ac9edde8273ed69c58874210ab092b181e

@osm0sis Should both system and system_root be present in it?

**Comment by fawazahmed0** [comment]
@Zackptg5 see here: <Removed so noobs won't find it>

**Comment by Zackptg5** [comment]
Gotcha. Osm0sis is looking into it :)

**Comment by Zackptg5** [comment]
@fawazahmed0 Osm0sis pushed a complete rewrite of mounting and looks solid so I'm hoping this will do the trick regardless of how system_root is implemented in twrp. Can you give this one a go?
[Disable_Dm-Verity_ForceEncrypt_08.18.2019.zip](https://github.com/Zackptg5/Disable_Dm-Verity_ForceEncrypt/files/3513113/Disable_Dm-Verity_ForceEncrypt_08.18.2019.zip)

**Comment by fawazahmed0** [comment]
@Zackptg5 This one works perfect. :+1:

**Comment by Zackptg5** [comment]
Awesome, thanks for the testing!
